### PR TITLE
Fixes for libuv undefined behavior

### PR DESCRIPTION
**Pull request by saghul**
3 tests are failing, same as master.

### CODE REVIEW

**Comment by joelpurra** [comment]
@saghul: the `master` build now passes tests on Travis (since #12, unless there's an unexpected timeout). I'd be happy to look into this pull request; it's next in line, as soon as I can find time. It might help if you find time to test/rebase the code though =)

**Comment by saghul** [comment]
ping?

**Comment by wtoorop** [comment]
pong... I can have a look too.  I'll try to do that this week.

**Comment by joelpurra** [comment]
@saghul: Tests are passing locally, so merging. (Travis is still assumed to be a bit flaky and needs to be examined/fixed.) Sorry that it took so long!

**Pull request merged**
